### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by sylwiavargas** [sruti/covid19-riskfactors-app#22]
**Action plan:**

- [x] **1. Move all state up to MainContainer**
- [x] change data into arrays of arrays
- [x] pass the data into the state
- [x] add key of showing to each object
- [x] **2. On the topmost level decide what’s passed down, in what order and what the points are**

**Why:** the lower components should be only getting the data and not be troubled with points

**THINGS I NOTICED:**
- [x] dyspnea does not have a title when handleClick sends the data — fix it, together with handleClick in MainContainer

**Comment by sylwiavargas** [comment]
@sruti currently, when on Mortality you select "ast/alt" and the first option, and then switch to ARDS, the first option never gets unclicked and that influences the number on the counter. I'm happy to fix it but I just don't know what should be showing in each of the pages in its place.
